### ISSUE TITLE
Bug in KendoGridBinder when you use datasource outside a grid

### ISSUE THREAD

**Issue by delossantosleandro** [rwhitmire/KendoGridBinder#14]
Hi, the binder code search items assuming order..

```
-                    Field1 = GetQueryStringValue(group[0]),
-                    Operator1 = GetQueryStringValue(group[1]),
-                    Value1 = GetQueryStringValue(group[2])
```

If you use the binder with combo box, the post came in diferent order.
-                    Field1 = GetValue(filterKeys, index, "field"),
-                    Operator1 = GetValue(filterKeys, index, "operator"),
-                    Value1 = GetValue(filterKeys, index, "value")

This works ok. I have no problem to make this fix, can can you give me some indications on how? (tests, etc.)

**Comment by StefH** [comment]
@delossantosleandro : I'm closing this issue. Please see [KendoGridBinderEx](https://github.com/StefH/KendoGridBinderEx) and check if this issue also exists there.
