### ISSUE TITLE
.NET Core ability

### ISSUE THREAD

**Issue by hchungi** [rwhitmire/KendoGridBinder#19]
Hello
Can this library support .NET Core?

**Comment by rwhitmire** [comment]
Unfortunately I don't have time to dedicate to this library at the moment. I'd be happy to add maintainers if anyone is interested in taking over.

**Comment by StefH** [comment]
I think I started porting my version https://github.com/StefH/KendoGridBinderEx , however I dont think its ready... I will take a quick look in some time...

**Comment by rwhitmire** [comment]
@StefH would you be interested in becoming the lead maintainer on this library and merging the two together? You've put a lot more time and effort into this than I have. If people are still using it, I think there could be value in a merge.

**Comment by StefH** [comment]
I would be interested in maintaining this project and also the NuGet. I can see if I can merge both projects and make this project & NuGet the main one.

**Comment by rwhitmire** [comment]
OK cool, I'll look into getting things set up next time I'm at my PC.

**Comment by rwhitmire** [comment]
You should now have push access and permission to publish the package on NuGet. Let me know if you need anything else.

**Comment by StefH** [comment]
@rwhitmire Access works for both NuGet and Github. In some time I'll starting moving/copying some code.

@hchungi Can you please try the latest from NuGet : https://www.nuget.org/packages/KendoGridBinderEx/5.0.2
